### ISSUE TITLE
[decouple] Config Report 0.2.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/configreport#102]
When taking care of a task (and marking as done), please add your name to the task!

### Reason

- Decouple release cycle from core

### Tasks

- [x] align master with stable10 so we can work solely on master in the future
- [x] lock stable10 branch
- [x] add dist target to Makefile https://github.com/owncloud/configreport/pull/103
- [x] create changelog https://github.com/owncloud/configreport/pull/103

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [ ] Create "$version Testplan"

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable)

### Publishing

- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number: https://github.com/owncloud/configreport/pull/106

**Comment by PVince81** [comment]
from what I see the diff between stable10 and master is very close.
somehow stable10 still has php 5.6 in there.

master already contains the updated phpunit stuff.

I'll lock stable10 then and we'll use master for future releases

@patrickjahns @phil-davis FYI

**Comment by PVince81** [comment]
0.2.0RC1: https://github.com/owncloud/configreport/releases/tag/v0.2.0RC1

**Comment by PVince81** [comment]
Tested with ownCloud 10.2.0 RC1 which bundles 0.2.0RC1:

- [x] TEST: configreport can be generated
- [x] TEST: configreport contains global mounts
- [ ] TEST: configreport only contains number of personal mounts :no_entry_sign:  => https://github.com/owncloud/configreport/issues/104

**Comment by PVince81** [comment]
0.2.0RC2: https://github.com/owncloud/configreport/releases/tag/v0.2.0RC2, problem solved with personal mounts

**Comment by PVince81** [comment]
final release: https://github.com/owncloud/configreport/releases/tag/v0.2.0
