### ISSUE TITLE
[QA] 0.3.0 Testplan

### ISSUE THREAD

**Issue by jnweiger** [owncloud/configreport#202]
## 'Configreport' Test Plan

Template: https://github.com/owncloud/QA/tree/master/Server/Test_Plan_configreport.md

## Setup
<details><summary>Setup details (click to view)</summary>

* `env OC10_DNSNAME=oc1091-cr021rc1-s3-DATE bash ./oc10.sh configreport files_antivirus wopi  metrics oauth2 richdocuments search_elastic user_ldap web windows_network_drive files_primary_s3`
  -> https://oc1091-cr021rc1-s3-20220320.jw-qa.owncloud.works

</details>

## Testing functionality

* [x] Sensitive data
   - configure a system with as many apps as possible that use credentials, internal addresses, ports, or path names.
   * [x] `occ configreport:generate` does not contain
      * [x] :no_entry: usernames or passwords -> #167
      * [x] environment variables in phpinfo section 
   * [x] the report contains
      * [x] hostnames or ip addresses or ports of connected services.
      * [x] pathnames used in the host system
      * [x] app config data of all installed apps (disabled / enabled are marked as active: false/true)
      * [ ] a merge of all config/config.php* files -> #166
      * [x] statistics about users and groups
      * [x] grace_period 1720012112 starting time.
* [x] Consistency
   - Numbers agree with
   * [x] Admin UI: User total and guest counts, ldap counts
   * [x] Admin UI: group counts. (off by one is okayis)
   * [x] Admin UI: generic, integrity checker results
   * [x] Admin UI: external storage mounts
   * [x] :no_entry: section phpinfo is non-empty and agrees with `php -r "phpinfo();"` -> #168
----

* [ ] https://github.com/owncloud/configreport/pull/197
  - [x] no exposed secrets, (licensekey *is* exposed)
  - [x] unchangeable receiver
  - [x] cron interval daily
  - [x] no telemetry is sent, when 
     - [x] opt-out `occ config:system:set telemetry.enabled --type boolean --value false`
     - [x] community edition, license-key is empty.
     - [ ] demo license key??
  - [x] telemetry submission is logged as `info`.
  - [ ] :no_entry: optional email-cc, subject: "Telemetry report from ". -> #205 
  - [ ] app-usage-stats
  - [x] estimates of active-users, active guests
  - [ ] count of local user/group shares, received/sent federated shares, number of federated peers.
  - [ ] receiving site honors GDPR / DSGVO
  - [x] it is transparent to the admin, what is being sent. 
  - [x] Documentation page is available and linked to from the release notes.

**Comment by jnweiger** [comment]
QA passed with some defects:
- no email option, 
- no app usage statistics,
- no data processing statement for the sensitive data sent.
